<<<<<<< HEAD
version: '3'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/crm-chatbot
    depends_on:
      - mongodb
    volumes:
      - ./src/uploads:/usr/src/app/src/uploads
    restart: always
  
  mongodb:
    image: mongo:5.0
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    restart: always

volumes:
  mongodb_data:
=======
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crm-chatbot:latest
    container_name: crm-chatbot-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/crm-chatbot
      - JWT_SECRET=${JWT_SECRET:-changeme_in_production}
      - JWT_EXPIRES_IN=7d
      - RATE_LIMIT_WINDOW=15
      - RATE_LIMIT_MAX=100
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    volumes:
      - ./uploads:/usr/src/app/uploads
      - app_logs:/usr/src/app/logs
    depends_on:
      - mongo
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo:
    image: mongo:6-jammy
    container_name: crm-chatbot-mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME:-}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - crm-network
    command: ["--auth", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  mongo-express:
    image: mongo-express:latest
    container_name: crm-chatbot-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME:-}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD:-}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-admin}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-pass}
    depends_on:
      - mongo
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  app_logs:
    driver: local
>>>>>>> 09232ac7148e18043e8bcbb4b7a57e9bab3d842c
